package app.tich.buildandrun.presentation.app

import app.tich.buildandrun.presentation.app.core.resolveText
import app.tich.buildandrun.presentation.i18n.UiText
import app.tich.buildandrun.resources.*

data class KanbanLabels(
    val open: String,
    val openInEditor: String,
    val openIn: String,
    val openInTerminal: String,
    val showInFinder: String,
    val configureEditors: String,
    val rememberEditorChoice: String,
    val forgetEditorChoice: String,
    val newWorktree: String,
    val finder: String,
    val terminal: String,
    val refresh: String,
    val ok: String,
    val push: String,
    val pull: String,
    val viewPullRequest: String,
    val createPullRequest: String,
    val lock: String,
    val unlock: String,
    val finishWorktree: String,
    val removeWorktree: String,
    val refreshStatus: String,
    val noConfiguredEditors: String,
    val clean: String,
    val modified: String,
    val notPushed: String,
    val loadingStatus: String,
    val noTasks: String,
    val addTask: String,
    val tasks: String,
    val selectProjectOrWorktree: String,
    val chooseItemFromSidebar: String,
    val taskTitle: String,
    val descriptionOptional: String,
    val appTitle: String,
    val worktrees: String,
    val prShort: String,
    val uncommittedChanges: String,
    val prMerged: String,
    val deleteAction: String,
    val editTaskAction: String,
    val saveAction: String,
    val moveTo: String,
    val markdownSupported: String,
    val selectWorktreeHint: String,
    val badgeMain: String,
    val badgeLocked: String,
    val copyPath: String,
    val createWorktreeTitle: String,
    val createWorktreeName: String,
    val createBranchNew: String,
    val createBranchExisting: String,
    val createBranchName: String,
    val createBaseBranch: String,
    val createLoadingBranches: String,
    val createLocation: String,
    val createButton: String,
    val createCancel: String,
    val createPreparing: String,
    val createSubmitting: String,
    val createBranchPicker: String,
    val completeWorktreeTitle: String,
    val completeWorktreeQuestion: String,
    val completeWorktreeCleanupOptions: String,
    val completeWorktreeDeleteLocalBranch: String,
    val completeWorktreeDeleteRemoteBranch: String,
    val completeWorktreeForceDelete: String,
    val completeWorktreeWarningUncommittedChanges: String,
    val completeWorktreeWarningOpenPr: String,
    val completeWorktreeCancel: String,
    val completeWorktreeDelete: String,
    val completeWorktreeComplete: String,
    val completeWorktreePreparing: String,
    val completeWorktreeSubmitting: String,
    val branchConflictTitle: String,
    val branchConflictUseExisting: String,
    val branchConflictRecreate: String,
    val branchConflictRecreateDetail: String,
    val toolbarNewWorktree: String,
    val toolbarFinder: String,
    val toolbarTerminal: String,
    val toolbarRefresh: String,
    val backToBoard: String,
    val createTask: String,
)

internal fun buildKanbanLabels(): KanbanLabels =
    KanbanLabels(
        open = resolveText(text = UiText(resource = Res.string.action_open)),
        openInEditor = resolveText(text = UiText(resource = Res.string.action_open_in_editor)),
        openIn = resolveText(text = UiText(resource = Res.string.action_open_in)),
        openInTerminal = resolveText(text = UiText(resource = Res.string.action_open_in_terminal)),
        showInFinder = resolveText(text = UiText(resource = Res.string.action_show_in_finder)),
        configureEditors = resolveText(text = UiText(resource = Res.string.action_configure_editors)),
        rememberEditorChoice = resolveText(text = UiText(resource = Res.string.action_remember_editor_choice)),
        forgetEditorChoice = resolveText(text = UiText(resource = Res.string.action_forget_editor_choice)),
        newWorktree = resolveText(text = UiText(resource = Res.string.action_new_worktree)),
        finder = resolveText(text = UiText(resource = Res.string.action_finder)),
        terminal = resolveText(text = UiText(resource = Res.string.action_terminal)),
        refresh = resolveText(text = UiText(resource = Res.string.action_refresh)),
        ok = resolveText(text = UiText(resource = Res.string.action_ok)),
        push = resolveText(text = UiText(resource = Res.string.action_push)),
        pull = resolveText(text = UiText(resource = Res.string.action_pull)),
        viewPullRequest = resolveText(text = UiText(resource = Res.string.action_view_pull_request)),
        createPullRequest = resolveText(text = UiText(resource = Res.string.action_create_pull_request)),
        lock = resolveText(text = UiText(resource = Res.string.action_lock)),
        unlock = resolveText(text = UiText(resource = Res.string.action_unlock)),
        finishWorktree = resolveText(text = UiText(resource = Res.string.action_finish_worktree)),
        removeWorktree = resolveText(text = UiText(resource = Res.string.action_remove_worktree)),
        refreshStatus = resolveText(text = UiText(resource = Res.string.action_refresh_status)),
        noConfiguredEditors = resolveText(text = UiText(resource = Res.string.detail_no_configured_editors)),
        clean = resolveText(text = UiText(resource = Res.string.detail_clean)),
        modified = resolveText(text = UiText(resource = Res.string.detail_modified)),
        notPushed = resolveText(text = UiText(resource = Res.string.detail_not_pushed)),
        loadingStatus = resolveText(text = UiText(resource = Res.string.detail_loading_status)),
        noTasks = resolveText(text = UiText(resource = Res.string.detail_no_tasks)),
        addTask = resolveText(text = UiText(resource = Res.string.action_add_task)),
        tasks = resolveText(text = UiText(resource = Res.string.detail_tasks)),
        selectProjectOrWorktree = resolveText(text = UiText(resource = Res.string.detail_select_project_or_worktree)),
        chooseItemFromSidebar = resolveText(text = UiText(resource = Res.string.detail_choose_item_from_sidebar)),
        taskTitle = resolveText(text = UiText(resource = Res.string.detail_task_title)),
        descriptionOptional = resolveText(text = UiText(resource = Res.string.detail_description_optional)),
        appTitle = resolveText(text = UiText(resource = Res.string.detail_app_title)),
        worktrees = resolveText(text = UiText(resource = Res.string.detail_worktrees)),
        prShort = resolveText(text = UiText(resource = Res.string.detail_pr_short)),
        uncommittedChanges = resolveText(text = UiText(resource = Res.string.detail_uncommitted_changes)),
        prMerged = resolveText(text = UiText(resource = Res.string.detail_pr_merged)),
        deleteAction = resolveText(text = UiText(resource = Res.string.action_delete)),
        editTaskAction = resolveText(text = UiText(resource = Res.string.action_edit_task)),
        saveAction = resolveText(text = UiText(resource = Res.string.action_save)),
        moveTo = resolveText(text = UiText(resource = Res.string.action_move_to)),
        markdownSupported = resolveText(text = UiText(resource = Res.string.detail_markdown_supported)),
        selectWorktreeHint = resolveText(text = UiText(resource = Res.string.detail_select_worktree_hint)),
        badgeMain = resolveText(text = UiText(resource = Res.string.detail_badge_main)),
        badgeLocked = resolveText(text = UiText(resource = Res.string.detail_badge_locked)),
        copyPath = resolveText(text = UiText(resource = Res.string.action_copy_path)),
        createWorktreeTitle = resolveText(text = UiText(resource = Res.string.worktree_create_title)),
        createWorktreeName = resolveText(text = UiText(resource = Res.string.worktree_create_name)),
        createBranchNew = resolveText(text = UiText(resource = Res.string.worktree_create_branch_new)),
        createBranchExisting = resolveText(text = UiText(resource = Res.string.worktree_create_branch_existing)),
        createBranchName = resolveText(text = UiText(resource = Res.string.worktree_create_branch_name)),
        createBaseBranch = resolveText(text = UiText(resource = Res.string.worktree_create_base_branch)),
        createLoadingBranches = resolveText(text = UiText(resource = Res.string.worktree_create_loading_branches)),
        createLocation = resolveText(text = UiText(resource = Res.string.worktree_create_location)),
        createButton = resolveText(text = UiText(resource = Res.string.worktree_create_button)),
        createCancel = resolveText(text = UiText(resource = Res.string.worktree_create_cancel)),
        createPreparing = resolveText(text = UiText(resource = Res.string.worktree_create_preparing)),
        createSubmitting = resolveText(text = UiText(resource = Res.string.worktree_create_submitting)),
        createBranchPicker = resolveText(text = UiText(resource = Res.string.worktree_create_branch_picker)),
        completeWorktreeTitle = resolveText(text = UiText(resource = Res.string.worktree_complete_title)),
        completeWorktreeQuestion = resolveText(text = UiText(resource = Res.string.worktree_complete_question)),
        completeWorktreeCleanupOptions = resolveText(text = UiText(resource = Res.string.worktree_complete_cleanup_options)),
        completeWorktreeDeleteLocalBranch =
            resolveText(text = UiText(resource = Res.string.worktree_complete_delete_local_branch)),
        completeWorktreeDeleteRemoteBranch =
            resolveText(text = UiText(resource = Res.string.worktree_complete_delete_remote_branch)),
        completeWorktreeForceDelete = resolveText(text = UiText(resource = Res.string.worktree_complete_force_delete)),
        completeWorktreeWarningUncommittedChanges =
            resolveText(text = UiText(resource = Res.string.worktree_complete_warning_uncommitted_changes)),
        completeWorktreeWarningOpenPr = resolveText(text = UiText(resource = Res.string.worktree_complete_warning_open_pr)),
        completeWorktreeCancel = resolveText(text = UiText(resource = Res.string.worktree_complete_cancel)),
        completeWorktreeDelete = resolveText(text = UiText(resource = Res.string.worktree_complete_delete)),
        completeWorktreeComplete = resolveText(text = UiText(resource = Res.string.worktree_complete_complete)),
        completeWorktreePreparing = resolveText(text = UiText(resource = Res.string.worktree_complete_preparing)),
        completeWorktreeSubmitting = resolveText(text = UiText(resource = Res.string.worktree_complete_submitting)),
        branchConflictTitle = resolveText(text = UiText(resource = Res.string.branch_conflict_title)),
        branchConflictUseExisting = resolveText(text = UiText(resource = Res.string.branch_conflict_use_existing)),
        branchConflictRecreate = resolveText(text = UiText(resource = Res.string.branch_conflict_recreate)),
        branchConflictRecreateDetail = resolveText(text = UiText(resource = Res.string.branch_conflict_recreate_detail)),
        toolbarNewWorktree = resolveText(text = UiText(resource = Res.string.toolbar_new_worktree)),
        toolbarFinder = resolveText(text = UiText(resource = Res.string.toolbar_finder)),
        toolbarTerminal = resolveText(text = UiText(resource = Res.string.toolbar_terminal)),
        toolbarRefresh = resolveText(text = UiText(resource = Res.string.toolbar_refresh)),
        backToBoard = resolveText(text = UiText(resource = Res.string.detail_back_to_board)),
        createTask = resolveText(text = UiText(resource = Res.string.detail_create_task)),
    )
